# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               DTC Playbook
tagline:             "by Matt Bahr"
description:         "Random ramblings / how to's on all things e-commerce and direct-to-consumer"
url:                 https://dtcplaybook.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Matt Bahr
  url:               https://twitter.com/mattrbahr
  email:             mattrbahr@gmail.com

# Custom vars
version:             1.0.0
